### ISSUE TITLE
Override Newrelic application name

### ISSUE THREAD

**Issue by kzacharakis** [Workable/orka#107]
Currently, the application name that we report to new relic is based on the `NODE_ENV` env variable. Apps that set this var to `production` in staging as well have no way to report in different account per environment (stg1, stg2 etc)

Let's change the rule to consult a `NEW_RELIC_APP_NAME` env var before

**Comment by nikostoulas** [comment]
Maybe we could make the honeybadger env more generic. Instead of honeybadger specific name it app env.
```js 
app: {
  name: 'app',
  env:'staging'
}```
APP_ENV will default to NODE_ENV like honeybadger environment now does but someone could override it.

**Comment by nikostoulas** [comment]
Config is available where newrelic initializer is called https://github.com/Workable/orka/blob/master/src/builder.ts#L43. 
So to make things easier there we could pass config and use the mentioned above config.app.env.

**Comment by nikostoulas** [comment]
Also linked https://github.com/Workable/diamorphosis/issues/11
