### ISSUE TITLE
json-appender should handle circular json

### ISSUE THREAD

**Issue by alkiskal** [Workable/orka#109]
https://github.com/Workable/orka/blob/38e86156fcc973f16176e788d7472dcd1bcfede1/src/initializers/log4js/json-appender.ts#L7

JSON.stringify cannot handle circular json. Maybe this could be of use

https://stackoverflow.com/a/18354289/1138559

**Comment by nikostoulas** [comment]
@manoskouvarakis  wasn't this fixed?

**Comment by manoskouvarakis** [comment]
Yes it is
