### ISSUE TITLE
Read visitor cookie id

### ISSUE THREAD

**Issue by nikostoulas** [Workable/orka#11]
This will be optional and used by apps that need it only

**Comment by SokratisVidros** [comment]
That's right. I will fix it next week!

**Comment by anastasios-workable** [comment]
FYI implemented @ https://github.com/Workable/application-form/blob/master/src/app/middlewares/visitor.ts

**Comment by alkiskal** [comment]
what about this? should someone copy it in orka?

**Comment by alkiskal** [comment]
I believe this can be closed @nikostoulas

**Comment by nikostoulas** [comment]
Yeap. Closing.
