### ISSUE TITLE
Setting blacklistedErrorCodes via environment not possible

### ISSUE THREAD

**Issue by echetzakis** [Workable/orka#127]
Setting the environment variable `BLACKLISTED_ERROR_CODES` 
to a value like `'400,401,403,404'` has no effect because the value is translated (from diamorphosis) to a string array
```
config.blacklistedErrorCodes = [ '400', '401', '403', '404']
```
which makes the `isBlacklisted` to return false because of the `type` inequality 
https://github.com/Workable/orka/blob/7bb54821b3733a8481e1819c8cadf792fb9de348/src/initializers/koa/error-handler.ts#L9

**Comment by alkiskal** [comment]
This is now resolved by not checking with strict equality.  Moreover, I've opened this https://github.com/Workable/diamorphosis/issues/12 . This is now resolved.

**Comment by nikostoulas** [comment]
Closing this as it is resolved
