### ISSUE TITLE
Automatically log visitor cookie in riviere context

### ISSUE THREAD

**Issue by klouvas** [Workable/orka#187]
Since all applications should log the visitor cookie as a  distributed tracing mechanism, couldn't we use the `visitor.orka` configuration flag to add by default in the riviere `context` the `visitor` value?

**Comment by nikostoulas** [comment]
This could be as easy as changing the default context here: https://github.com/Workable/orka/blob/master/src/default-options.ts#L49.
Apps that don't overwrite this will have it by default

**Comment by klouvas** [comment]
i was thinking something more like the example PR i made.
