### ISSUE TITLE
Support pg initialization

### ISSUE THREAD

**Issue by nikostoulas** [Workable/orka#5]

**Comment by alkiskal** [comment]
I could do the initializations (pg, rabbit, mongo). We could add aws and elastic as well.

**Comment by klesgidis** [comment]
We can add kafka as well

**Comment by nikostoulas** [comment]
Sure. Actually, we probably should since more and more apps will need it.

**Comment by alkiskal** [comment]
@nikostoulas @klesgidis this is old. mongo, rabbit, kafka have been added. I don't know about pg though. It could cause problems since everyone is using different libraries to interact with postgres
(pg-then, pg-promise, knex etc).

**Comment by klesgidis** [comment]
https://github.com/Workable/orka/pull/255
