### ISSUE TITLE
Is new relic initialised properly?

### ISSUE THREAD

**Issue by echetzakis** [Workable/orka#64]
We've added Orka to our VHS project and on new relic web app we get the following warning
```
Some modules were uninstrumented during the current time window: q, 
mongodb, bluebird, aws-sdk, koa-route, koa, koa-router, amqplib/channel_api.js,
 amqplib/channel_api, amqplib. 
Make sure require('newrelic'); is the first line of the application's main module.
```

**Comment by alkiskal** [comment]
Try importing the orka module first in your app.js

**Comment by echetzakis** [comment]
its (almost) already the case: https://github.com/Workable/vhs/blob/7edc8dcdcf16872f8c1cbdb072cb5bcc37bfd8df/app.js#L3

**Comment by alkiskal** [comment]
Let's try to make it exactly the case. I believe it won't fix it, but let's make it sure.
